[video]
filepath = "path/to/your/video.mp4"
frames = "" # make this an int input 

[h5]
filepath = "path/to/your/sleap/tracking/file.h5"

[rois]
# count = int 

[rois.names]
# 1 = "ROI1"
# the number of rois you name must match the value of count in the [rois] feild