[video]
filepath = "test_data/videos/test.mp4"
frames = "54,605" # FIXME: make this an int input 

[h5]
filepath = "test_data/h5s/test.h5"

[rois]
count = 3

[rois.names]
1 = "ButtonL"
2 = "ButtonR"
3 = "Reward"

[attention_vectors]
human_labled_frames = 20 
magnitude = 100

[markers]
anchor = "nose1"

[tests]
test_frame = 13766